# Generated by Django 4.2.7 on 2025-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alumni_membership_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('outreach', 'Community Outreach'), ('leadership', 'Leadership & Academic'), ('innovation', 'Innovation & Entrepreneurship'), ('partnership', 'Partnerships & Collaborations')], default='outreach', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_details',
            field=models.TextField(blank=True, help_text='e.g., 50+ students supported, 200+ community members reached'),
        ),
    ]
