# Generated by Django 4.2.7 on 2025-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_project_category_project_impact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='author_name',
            field=models.CharField(blank=True, help_text='Author name to display (if different from created_by)', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', 'Association News'), ('articles', 'Articles & Reflections'), ('spotlights', 'Student Spotlights'), ('featured', 'Featured Post')], default='news', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description for preview', max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured post'),
        ),
    ]
