# Generated by Django 4.2.7 on 2025-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_newsletter_news_author_name_news_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SSSALU', max_length=100)),
                ('site_description', models.TextField(default='South Sudanese Student Association at African Leadership University')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('contact_address', models.TextField(default='African Leadership University, Kigali, Rwanda')),
                ('contact_email', models.EmailField(default='sssalu@alu.edu', max_length=254)),
                ('contact_phone', models.CharField(default='+250 123 456 789', max_length=20)),
                ('copyright_text', models.CharField(default='2023 South Sudanese Student Association - ALU. All rights reserved.', max_length=200)),
                ('newsletter_title', models.CharField(default='Subscribe to Our Newsletter', max_length=100)),
                ('newsletter_description', models.TextField(default='Stay updated with the latest news, events, and stories from the South Sudanese Student Association at ALU.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
