# Generated by Django 4.2.7 on 2025-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('cultural', 'Cultural Events'), ('academic', 'Academic Activities'), ('community', 'Community Service'), ('social', 'Social Gatherings'), ('featured', 'Featured Highlights')], default='cultural', max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='event_date',
            field=models.CharField(blank=True, help_text='e.g., May 2022, July 2023', max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured highlights section'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Mark as video content'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL for videos'),
        ),
    ]
