# Generated by Django 4.2.7 on 2025-06-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_gallery_category_gallery_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('cultural', 'Cultural Events'), ('academic', 'Academic Activities'), ('community', 'Community Service'), ('social', 'Social Gatherings'), ('featured', 'Featured Highlights'), ('event_gallery', 'Event Gallery')], default='cultural', max_length=50),
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alu_id', models.CharField(max_length=50)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=200)),
                ('additional_guests', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.event')),
            ],
        ),
    ]
