# Generated by Django 4.2.7 on 2025-12-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_event_status_alter_gallery_category_eventrsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('graduation_year', models.IntegerField()),
                ('program', models.CharField(max_length=100)),
                ('current_position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField()),
                ('expertise_areas', models.TextField(help_text='Areas of expertise (e.g., Software Development, Business Strategy)')),
                ('mentoring_experience', models.TextField(help_text='Previous mentoring experience')),
                ('availability', models.CharField(help_text='e.g., Weekends, Evenings', max_length=100)),
                ('motivation', models.TextField(help_text='Why do you want to become a mentor?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MentorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=20)),
                ('career_interests', models.TextField(help_text='Areas of career interest')),
                ('mentoring_goals', models.TextField(help_text='What do you hope to achieve through mentoring?')),
                ('preferred_mentor_background', models.TextField(help_text='Preferred mentor background or expertise')),
                ('availability', models.CharField(help_text='e.g., Weekends, Evenings', max_length=100)),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
    ]
